define([
  'spec/models/appPresenterSpec',
  'spec/models/dashboardPresenterSpec',
  'spec/models/protectedResourceSpec',
  'spec/models/taskSpec',
  'spec/models/userSpec',
  'spec/collections/protectedCollectionSpec',
  'spec/collections/taskCollectionSpec'
]);