define([
  'spec/views/partials/loginFormViewSpec',
  'spec/views/partials/dashboardHomeViewSpec',
  'spec/views/partials/dashboardSidebarViewSpec',
  'spec/views/partials/dashboardTopWidgetsViewSpec',
  'spec/views/partials/kanbanBoardViewSpec',
  'spec/views/partials/kanbanColumnViewSpec',
  'spec/views/partials/taskPanelViewSpec'
  ]);